<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BNIRTNQ" failures="1" tests="4" name="Test" time="49.052" errors="0" timestamp="2022-08-07T10:41:58 IST">
  <testcase classname="com.SauceDemo.TestClasses.TC02VerifyLogOutFunctionality" name="verifyLogOut" time="1.49"/>
  <testcase classname="com.SauceDemo.TestClasses.TC01VerifyLoginFunctionality" name="verifyLogin" time="0.105"/>
  <testcase classname="com.SauceDemo.TestClasses.TC03VerifyBagProductAddToCartFunctionality" name="verifyBagProductAddToCart" time="0.29"/>
  <testcase classname="com.SauceDemo.TestClasses.TC04VerifyMultipleProductAddToCarFunctionality" name="verifyMultipleProductAddToCart" time="1.096">
    <failure type="java.lang.AssertionError" message="expected [6] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [3]
at com.SauceDemo.TestClasses.TC04VerifyMultipleProductAddToCarFunctionality.verifyMultipleProductAddToCart(TC04VerifyMultipleProductAddToCarFunctionality.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyMultipleProductAddToCart -->
</testsuite> <!-- Test -->
